trigger: none  # Disable CI triggers

schedules:
- cron: "* * * * *"  # Run every 5 minutes
  displayName: Every 5 minutes
  branches:
    include:
    - main
  always: true

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_SUBSCRIPTION: '<Your Azure Subscription>'
  RESOURCE_GROUP: '<Your Resource Group>'
  VM_NAME: '<Your VM Name>'
  servicePrincipalId: '<Your Service Principal ID>'
  servicePrincipalKey: '<Your Service Principal Key>'
  tenantId: '<Your Tenant ID>'
jobs:
-  job: startVMjob
   displayName:  StartVM
   
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: '$(AZURE_SUBSCRIPTION)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Logging in to Azure..."
      az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
      
      echo "Starting the VM..."
      az vm start --resource-group $(RESOURCE_GROUP) --name $(VM_NAME)
      
      echo "VM started successfully!"
